### ISSUE TITLE
Start preparing for HLE rendering

### ISSUE THREAD

**Issue by Dudejoe870** [Ryu64Emulator/Ryu64#6]
# Task List
- [ ] Add a way to get the F3D Version / Extension. (probably through a checksum)
- [ ] Figure out a way to get currently executing F3D Microcode.
- [ ] Add a basic framework for a F3D interpreter.
